#!/usr/bin/env python3
# mkgfx.py - the sprites of the Watara Supervision examples, drawn as text
# pictures, turned into data for the Supervision screen: sprite_gfx.h,
# catch_gfx.h.
#
# The pictures are the same as for PC Engine, Mega Drive, Game Boy and Lynx
# (tools/pce, tools/md, tools/gb, tools/lynx); each character is a pen
# number ('.' = 0, background). The Supervision has no sprite hardware and
# only 4 shades: every pen is given a shade 0..3 (0 = background, the
# lightest; 3 = the darkest), and the program copies the picture into the
# screen memory itself.
#
# Screen memory: 48 bytes a line, 4 pixels a byte, 2 bits a pixel, the
# left pixel in the lowest two bits. A sprite at x lands at byte x / 4,
# shifted by x % 4 pixels, so every sprite is stored four times, already
# shifted by 0..3 pixels: (w/4 + 1) bytes a line, h lines each.

def shades(rows, pens, scale=1):
    out = []
    for r in rows:
        line = [pens.get(ch, 0) for ch in r]
        line = [v for v in line for _ in range(scale)]
        out += [line] * scale
    return out

def shifted(pix):
    h, w = len(pix), len(pix[0])
    wb = w // 4 + 1
    data = []
    for s in range(4):
        for line in pix:
            row = [0] * (s) + line + [0] * (wb * 4 - w - s)
            for b in range(wb):
                v = 0
                for i in range(4):
                    v |= row[b * 4 + i] << (2 * i)
                data.append(v)
    return data, wb, h

def array(name, data):
    lines = ['\t' + ', '.join('0x%02X' % b for b in data[i:i+12]) for i in range(0, len(data), 12)]
    return 'static const unsigned char %s[%d] = {\n' % (name, len(data)) + ',\n'.join(lines) + '\n};\n'

robot = [
"................",
".......11.......",
"......1111......",
"...2222222222...",
"...2333333332...",
"...2343334332...",
"...2333333332...",
"...2355555532...",
"...2222222222...",
".....222222.....",
"...2266666622...",
"..226666666622..",
"..2.66666666.2..",
"....22....22....",
"....22....22....",
"...222....222...",
]
ball = [
"................",
"................",
"......7777......",
"....77777777....",
"...7788777777...",
"...7887777777...",
"..778777777777..",
"..777777777777..",
"..777777777777..",
"..777777777777..",
"...7777777777...",
"...7777777777...",
"....77777777....",
"......7777......",
"................",
"................",
]
star = [
"................",
".......88.......",
".......88.......",
"......8998......",
"......8998......",
"88888899998888..",
".8889999999888..",
"..88899999888...",
"...889999988....",
"...888999888....",
"..8889888988....",
"..888.888.888...",
".888..8.8..888..",
".88.........88..",
"................",
"................",
]
basket = [
"................",
"................",
"................",
"................",
"................",
"................",
"AAAAAAAAAAAAAAAA",
"ABBBBBBBBBBBBBBA",
"ABABABABABABABBA",
".ABBBBBBBBBBBBA.",
".ABABABABABABBA.",
"..ABBBBBBBBBBA..",
"..ABABABABABBA..",
"...ABBBBBBBBA...",
"...AAAAAAAAAA...",
"................",
]

ROBOT  = {'1': 3, '2': 3, '3': 1, '4': 3, '5': 2, '6': 2}
ROBOT2 = {'1': 2, '2': 1, '3': 2, '4': 3, '5': 3, '6': 3}   # button A: other shades
BALL   = {'7': 2, '8': 1}
STAR   = {'8': 3, '9': 1}
BASKET = {'A': 3, 'B': 1}

def write(fn, items):
    with open(fn, 'w', newline='\n') as f:
        f.write('/* %s - generated by mkgfx.py, do not edit */\n\n' % fn)
        for name, rows, pens, scale in items:
            data, wb, h = shifted(shades(rows, pens, scale))
            f.write('/* %d bytes x %d lines, shifted by 0..3 pixels */\n' % (wb, h))
            f.write(array(name, data) + '\n')

write('sprite_gfx.h', [('robot1', robot, ROBOT, 1), ('robot1b', robot, ROBOT2, 1),
                       ('robot2', robot, ROBOT, 2), ('robot2b', robot, ROBOT2, 2),
                       ('ball', ball, BALL, 1)])
write('catch_gfx.h', [('basket', basket, BASKET, 1), ('star', star, STAR, 1)])
