#!/usr/bin/env python3
# mksprites.py - draws the sprites of the Atari Lynx examples as text pictures
# and writes them as sprite data for the Lynx sprite engine (Suzy):
# sprite_gfx.h, catch_gfx.h.
#
# The pictures are the same as for PC Engine and Mega Drive (tools/pce,
# tools/md). Each character is a pen number 0..F ('.' = 0, transparent).
# The sprites are "literal" (not packed), 4 bits a pixel: every line starts
# with a byte that says how many bytes the line takes (this byte included),
# then two pixels a byte, the left one in the high half; a 0 byte ends the
# sprite. One extra 0 byte at the end of each line works around a Suzy
# quirk that drops the last pixel of literal lines. Which colour each pen
# shows is chosen by the 8-byte pen palette in the sprite control block.

def sprite(name, rows):
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), name
    data = []
    for r in rows:
        pix = [0 if ch == '.' else int(ch, 16) for ch in r]
        line = [(pix[i] << 4) | pix[i + 1] for i in range(0, 16, 2)] + [0]
        data += [len(line) + 1] + line
    data.append(0)
    lines = ['\t' + ', '.join('0x%02X' % b for b in data[i:i+10]) for i in range(0, len(data), 10)]
    return 'unsigned char %s_spr[%d] = {\n' % (name, len(data)) + ',\n'.join(lines) + '\n};\n'

robot = [
"................",
".......11.......",
"......1111......",
"...2222222222...",
"...2333333332...",
"...2343334332...",
"...2333333332...",
"...2355555532...",
"...2222222222...",
".....222222.....",
"...2266666622...",
"..226666666622..",
"..2.66666666.2..",
"....22....22....",
"....22....22....",
"...222....222...",
]
ball = [
"................",
"................",
"......7777......",
"....77777777....",
"...7788777777...",
"...7887777777...",
"..778777777777..",
"..777777777777..",
"..777777777777..",
"..777777777777..",
"...7777777777...",
"...7777777777...",
"....77777777....",
"......7777......",
"................",
"................",
]
star = [
"................",
".......88.......",
".......88.......",
"......8998......",
"......8998......",
"88888899998888..",
".8889999999888..",
"..88899999888...",
"...889999988....",
"...888999888....",
"..8889888988....",
"..888.888.888...",
".888..8.8..888..",
".88.........88..",
"................",
"................",
]
basket = [
"................",
"................",
"................",
"................",
"................",
"................",
"AAAAAAAAAAAAAAAA",
"ABBBBBBBBBBBBBBA",
"ABABABABABABABBA",
".ABBBBBBBBBBBBA.",
".ABABABABABABBA.",
"..ABBBBBBBBBBA..",
"..ABABABABABBA..",
"...ABBBBBBBBA...",
"...AAAAAAAAAA...",
"................",
]

def write(fn, names):
    with open(fn, 'w', newline='\n') as f:
        f.write('/* %s - generated by mksprites.py, do not edit */\n\n' % fn)
        for n in names:
            f.write(sprite(n, globals()[n]) + '\n')

write('sprite_gfx.h', ['robot', 'ball'])
write('catch_gfx.h', ['basket', 'star'])
