#!/usr/bin/env python3
# mksprites.py - draws the sprites of the Mega Drive examples as text pictures
# and writes them as tile data for SGDK: sprite_gfx.h, catch_gfx.h.
#
# Each character is a colour number 0..F of the sprite palette ('.' = 0,
# transparent). The Mega Drive builds pictures from 8x8 tiles, 4 bits a
# pixel: a tile row is one 32-bit word, the leftmost pixel in the top four
# bits. A 16x16 sprite is 2x2 tiles, stored column by column: top left,
# bottom left, top right, bottom right.

def sprite(name, rows):
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), name
    words = []
    for tx, ty in ((0, 0), (0, 1), (1, 0), (1, 1)):
        for y in range(8):
            w = 0
            for x in range(8):
                ch = rows[ty * 8 + y][tx * 8 + x]
                v = 0 if ch == '.' else int(ch, 16)
                w |= v << (28 - 4 * x)
            words.append(w)
    lines = ['\t' + ', '.join('0x%08X' % w for w in words[i:i+8]) for i in range(0, 32, 8)]
    return 'const u32 %s_spr[32] = {\n' % name + ',\n'.join(lines) + '\n};\n'

robot = [
"................",
".......11.......",
"......1111......",
"...2222222222...",
"...2333333332...",
"...2343334332...",
"...2333333332...",
"...2355555532...",
"...2222222222...",
".....222222.....",
"...2266666622...",
"..226666666622..",
"..2.66666666.2..",
"....22....22....",
"....22....22....",
"...222....222...",
]
ball = [
"................",
"................",
"......7777......",
"....77777777....",
"...7788777777...",
"...7887777777...",
"..778777777777..",
"..777777777777..",
"..777777777777..",
"..777777777777..",
"...7777777777...",
"...7777777777...",
"....77777777....",
"......7777......",
"................",
"................",
]
star = [
"................",
".......88.......",
".......88.......",
"......8998......",
"......8998......",
"88888899998888..",
".8889999999888..",
"..88899999888...",
"...889999988....",
"...888999888....",
"..8889888988....",
"..888.888.888...",
".888..8.8..888..",
".88.........88..",
"................",
"................",
]
basket = [
"................",
"................",
"................",
"................",
"................",
"................",
"AAAAAAAAAAAAAAAA",
"ABBBBBBBBBBBBBBA",
"ABABABABABABABBA",
".ABBBBBBBBBBBBA.",
".ABABABABABABBA.",
"..ABBBBBBBBBBA..",
"..ABABABABABBA..",
"...ABBBBBBBBA...",
"...AAAAAAAAAA...",
"................",
]

def write(fn, names):
    with open(fn, 'w', newline='\n') as f:
        f.write('/* %s - generated by mksprites.py, do not edit */\n\n' % fn)
        for n in names:
            f.write(sprite(n, globals()[n]) + '\n')

write('sprite_gfx.h', ['robot', 'ball'])
write('catch_gfx.h', ['basket', 'star'])
