#!/usr/bin/env python3
# mksprites.py - draws the sprites of the Game Boy examples as text pictures
# and writes them as tile data for GBDK: sprite_gfx.h, catch_gfx.h.
#
# The pictures are the same as for PC Engine and Mega Drive (tools/pce,
# tools/md), but the Game Boy has only four shades: each sprite has a map
# from its colour digits to a shade (0 = transparent, 1 light, 2 dark,
# 3 black). Tiles are 8x8, 2 bits a pixel: a row is two bytes, the low and
# the high bit of each pixel, bit 7 is the leftmost pixel. The examples use
# 8x16 sprites, so a 16x16 picture is two hardware sprites side by side:
# tiles left-top, left-bottom, right-top, right-bottom.

def sprite(name, rows, shades):
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), name
    data = []
    for tx in (0, 1):
        for ty in (0, 1):
            for y in range(8):
                lo = hi = 0
                for x in range(8):
                    ch = rows[ty * 8 + y][tx * 8 + x]
                    v = 0 if ch == '.' else shades[ch]
                    lo |= (v & 1) << (7 - x)
                    hi |= (v >> 1) << (7 - x)
                data += [lo, hi]
    lines = ['\t' + ', '.join('0x%02X' % b for b in data[i:i+16]) for i in range(0, 64, 16)]
    return 'const unsigned char %s_spr[64] = {\n' % name + ',\n'.join(lines) + '\n};\n'

robot = [
"................",
".......11.......",
"......1111......",
"...2222222222...",
"...2333333332...",
"...2343334332...",
"...2333333332...",
"...2355555532...",
"...2222222222...",
".....222222.....",
"...2266666622...",
"..226666666622..",
"..2.66666666.2..",
"....22....22....",
"....22....22....",
"...222....222...",
]
ball = [
"................",
"................",
"......7777......",
"....77777777....",
"...7788777777...",
"...7887777777...",
"..778777777777..",
"..777777777777..",
"..777777777777..",
"..777777777777..",
"...7777777777...",
"...7777777777...",
"....77777777....",
"......7777......",
"................",
"................",
]
star = [
"................",
".......88.......",
".......88.......",
"......8998......",
"......8998......",
"88888899998888..",
".8889999999888..",
"..88899999888...",
"...889999988....",
"...888999888....",
"..8889888988....",
"..888.888.888...",
".888..8.8..888..",
".88.........88..",
"................",
"................",
]
basket = [
"................",
"................",
"................",
"................",
"................",
"................",
"AAAAAAAAAAAAAAAA",
"ABBBBBBBBBBBBBBA",
"ABABABABABABABBA",
".ABBBBBBBBBBBBA.",
".ABABABABABABBA.",
"..ABBBBBBBBBBA..",
"..ABABABABABBA..",
"...ABBBBBBBBA...",
"...AAAAAAAAAA...",
"................",
]

# colour digit -> Game Boy shade
shades = {
    'robot':  {'1': 2, '2': 3, '3': 1, '4': 3, '5': 2, '6': 2},
    'ball':   {'7': 2, '8': 1},
    'star':   {'8': 3, '9': 1},
    'basket': {'A': 3, 'B': 2},
}

def write(fn, names):
    with open(fn, 'w', newline='\n') as f:
        f.write('/* %s - generated by mksprites.py, do not edit */\n\n' % fn)
        for n in names:
            f.write(sprite(n, globals()[n], shades[n]) + '\n')

write('sprite_gfx.h', ['robot', 'ball'])
write('catch_gfx.h', ['basket', 'star'])
